driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

platforms:
  - name: centos-6
  - name: centos-7
  - name: debian-8
    run_list: apt::default
  - name: debian-9
    run_list: apt::default
  - name: freebsd-10
  - name: freebsd-11
  - name: fedora-28
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-16.04
    run_list: apt::default

suites:
- name: source
  run_list:
  - recipe[passenger_apache2]

- name: package
  run_list:
  - recipe[passenger_apache2_test::package]
  - recipe[passenger_apache2]
  excludes: ["centos-6", "centos-7", "fedora-28"]

- name: version-override
  run_list:
  - recipe[passenger_apache2]
  excludes: ["centos-6", "centos-7", "fedora-28"]
  attributes:
    passenger:
      version: "4.0.5"
      module_path: "/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/passenger-4.0.5/libout/apache2/mod_passenger.so"
